### ISSUE TITLE
Pin underlying AMI

### ISSUE THREAD

**Issue by crmejia** [FairwindsOps/terraform-bastion#33]
If the underlying AMI changes it forces a change on the state. Which is not desired since the version of the bastion module has not rolled. Pinning said AMI would fix the issue.

**Comment by sudermanjr** [comment]
I'm not a big fan of this actually. @ivanfetch and I talked about this when he created the module and we feel that it's better to keep the AMI as up to date as possible. This ensures that we get all security patches, especially considering that this is a public endpoint.

**Comment by crmejia** [comment]
I agree that it's important to keep up to date but I feel we get a side-effect that might have unintended consequences. It would be nice if we have a bot that added a minor version and changed the underlying AMI.

Closing as this is intended by design.
