### ISSUE TITLE
Convert default instance size to t3 for AWS

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/terraform-bastion#36]

**Comment by ivanfetch** [comment]
@mdgreenwald mentioned this during nov 12 2020 engineering office hours, setting the default instance type to use the T3 family.

We also want to make sure the CPU Credits option is set to mirror the default T2 instance type behavior (it's ok to run out of credits), so the bastion cost is predictable.

**Comment by mdgreenwald** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#credit-specification

**Comment by mdgreenwald** [comment]
This also may require switching to [launch templates](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template).
