### ISSUE TITLE
Can't start bastion with AWS key generated from terraform

### ISSUE THREAD

**Issue by Toilal** [FairwindsOps/terraform-bastion#59]
**Is your feature request related to a problem? Please describe.**
If wish to generate SSH Key pair from AWS and keep generated private and public key inside terraform state with the following configuration.

```terraform
resource "tls_private_key" "bastion" {
  algorithm = "RSA"
}

resource "aws_key_pair" "bastion" {
  key_name   = "bastion"
  public_key = tls_private_key.bastion.public_key_openssh
}
```

Then I try to reference the public key inside bastion module.

```terraform
module "bastion" {
  # ...
  ssh_public_key_file = aws_key_pair.bastion.public_key
  # ...
}
```

But this doesn't work, because of changes brought in  #52, it raise this error.

```
Error: Invalid count argument
│ 
│   on .terraform/modules/bastion/aws/ssh-keypair.tf line 2, in resource "aws_key_pair" "bastion":
│    2:   count = var.ssh_public_key_file == "" ? 0 : 1
│ 
│ The "count" value depends on resource attributes that cannot be determined
│ until apply, so Terraform cannot predict how many instances will be created.
│ To work around this, use the -target argument to first apply only the
│ resources that the count depends on.
```

**Describe the solution you'd like**

There should be a way to manually define `key_name` parameter of launchconfiguration resource

https://github.com/FairwindsOps/terraform-bastion/blob/17f6c968d7316dfb90f28e8a484f962dd997b127/aws/launchconfig.tf#L38

User could write this configuration.

```terraform
module "bastion" {
  # ...
  ssh_key_name = aws_key_pair.bastion.key_name
  # ...
}
```

**Describe alternatives you've considered**
I can't see any other alternative.

**Additional context**

**Comment by ivanfetch-fw** [comment]
Closing this issue as its PR has been merged.
