### ISSUE TITLE
[aws] Would you consider an openvpn option ?

### ISSUE THREAD

**Issue by Toilal** [FairwindsOps/terraform-bastion#64]
**Is your feature request related to a problem? Please describe.**

No problem, but it could make sense to bring OpenVPN into the bastion as an optional feature. Would you consider a pull request ?

**Describe the solution you'd like**

Set `bastion_openvpn = true` as input. This would spawn an OpenVPN instance and generate `*.ovpn` client configuration files for each bastion user. This should also allow options like `bastion_openvpn_protocol` (`tcp` or `udp`) and `bastion_openvpn_port`.

**Describe alternatives you've considered**
Some opensource modules provides OpenVPN, but they are often to heavy for a temporary instance. For user of `FairwindsOps/terraform-bastion` who want a VPN access to VPC, it seems to make sense to install it right inside the bastion instance.

**Additional context**
I implement OpenVPN inside bastion using [angristan/openvpn-install](https://github.com/angristan/openvpn-install) in my project.

**Comment by ivanfetch-fw** [comment]
Hello, thank you for this suggestion. We would prefer not to configure VPNs directly in the bastion module at this time. Using [sshuttle](https://sshuttle.readthedocs.io/en/stable/) is meeting our VPN-like needs while keeping maintenance low for this module and for potential security vulnerabilities.
