### ISSUE TITLE
cloud-init apt error with ubuntu 20.04

### ISSUE THREAD

**Issue by Toilal** [FairwindsOps/terraform-bastion#65]
### What happened?

`/var/log/cloud-init-output.log` show that an error occurs when running bastion.

```
Setting up libpaper1:amd64 (1.1.28) ...
Error: Only one of force_conffold and force_conffnew should
       be set
dpkg: error processing package libpaper1:amd64 (--configure):
 installed libpaper1:amd64 package post-installation script subprocess returned error exit status 1
```

### What did you expect to happen?

No error

### How can we reproduce this?

- terraform apply.
- ssh into bastion.
- run `cloud-init status --wait` (this display an error).
- run `cat /var/log/cloud-init-output.log` and you should see the apt error .

### version

master

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

This occurs in both ubuntu 18.04 and 20.04

**Comment by Toilal** [comment]
I have updated the issue after testing in ubuntu 18.04, it also occurs.

**Comment by ivanfetch-fw** [comment]
Reopening as we should fix this.
