### ISSUE TITLE
cloud-init is always in error (code 1) because of last command

### ISSUE THREAD

**Issue by Toilal** [FairwindsOps/terraform-bastion#66]
### What happened?

Last command of UserData is `test -r /var/run/reboot-required && echo Reboot is required, doing that now... && shutdown -r now`.

Problem is that this command exit with error code 1 when no `reboot-required` file is missing, causing UserData script itself to exit with error code 1.

if; then; fi statement should be used to avoid this.

### What did you expect to happen?

UserData script should exit with code 0, so that `cloud-init status` command doesn't report an error.

### How can we reproduce this?

Run `cloud-init status` in a refresh bastion that doesn't require a reboot after running UserData script.

### version

master

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ivanfetch-fw** [comment]
Closing this issue as its PR has been merged.
