### ISSUE TITLE
IPv6 Connectivity

### ISSUE THREAD

**Issue by Toilal** [FairwindsOps/terraform-bastion#69]
**Is your feature request related to a problem? Please describe.**

Bastion should be available through ipv6 (when running in a VPC properly configured for ipv6 of course)

**Describe the solution you'd like**

- `curl -6 https://ifconfig.co` should work properly in the bastion.
- A user should be able to connect with SSH using an IPv6 interface.

**Describe alternatives you've considered**

**Additional context**

**Comment by lucasreed** [comment]
Thank you for this proposal and PR!
